name: onebeauty
version: 0.0.1

models:
  - name: gpt-oss-120b
    provider: openai
    model: openai/gpt-oss-120b
    apiBase: https://apionebeautyspace.kirilovdmitry7.workers.dev
    # ключ кладём прямо сюда, чтобы исключить проблемы с секретами/ENV
    apiKey: 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
    completionOptions:
      stream: false
      temperature: 0.2
      maxTokens: 4096

chatModel: gpt-oss-120b
editModel: gpt-oss-120b
tabAutocompleteModel: gpt-oss-120b